articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail')
]

testBlog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('articles.urls')),
    path('admin/', admin.site.urls),
]

articles/models.py
import datetime
from django.db import models
from django.utils import timezone


# Create your models here.


class Article(models.Model):
    title = models.CharField('Article title', max_length=100)
    text = models.TextField('Article text')
    date = models.DateTimeField('Publish date')

    def __str__(self):
        return self.title

    def is_recently(self):
        return self.date >= (timezone.now() - datetime.timedelta(days=7))


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.CharField('Author', max_length=100)
    text = models.TextField('Comment text', max_length=1000)

articles/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render
from .models import Article, Comment


def index(request):
    latest_list = Article.objects.order_by('-date')[:5]
    return render(request, 'articles/list.html', {"latest_list": latest_list})


def detail(request, pk):
    try:
        a = Article.objects.get(id=pk)
    except:
        raise Http404("No articles")

    return render(request, 'articles/detail.html', {'article': a})

templates/articles/detail.html
{% extends 'base.html' %}

{% block title %}
    {{ article.title}}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <h2>{{ article.title }}</h2>
        <p>{{ article.text }}</p>
        <em>{{ article.date }}</em>
        <hr>
    </div>
{% endblock %}

templates/articles/list.html
{% extends 'base.html' %}

{% block title %}
Last articles
{% endblock %}

{% block content %}
    <h1 class="mt-5, mx-5">Articles List</h1>
    <div class="container mt-5">
    {% if latest_list %}
        <ul>
        {% for latest in latest_list %}
           <li><a href="{% url 'articles:detail' latest.pk%}">{{ latest.title }}</a></li>
        {% endfor %}
        </ul>
    {% endif %}
    </div>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>{% block title %}Hello, world!{% endblock %}</title>
  </head>
  <body style="background-color: #008080">
        {% block content %}

        {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>